version: "3.8"
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
  ports: 
   - 9200:9200
   - 9300:9300
  environment:
   - discovery.type=single-node
  volumes:
   - elasticsearch:/usr/share/elasticsearch/data
volumes:
 elasticsearch: 
